const apiEndpoint = "https://offers-server.herokuapp.com/1.0.0/offers";
const appName = "Onde tem Oferta?";
const appNameFont = "Lobster";
const citySharedPreferenceId = "city";
const errorText = "Erro";
const loadingText = "Carregando...";
const noOffersText = "Sem ofertas";
const selectCityText = "Selecione a cidade";
const youAreNotConnectedText = "Você não está conectado";
